"use client";

export default function TermsAndConditions() {
  return (
    <section className="w-full flex justify-center py-10 grow">
      <div className="max-w-6xl w-full px-5 sm:px-8 lg:px-10 py-16 space-y-12">

        {/* Page Heading */}
        <h1 className="text-3xl sm:text-4xl lg:text-5xl text-[#011642] font-bold tracking-wide text-center leading-snug">
          Terms of Service
          <span className="block text-xl sm:text-2xl text-[#595959] mt-2">
            Growsharp Technologies Pvt. Ltd.
          </span>
        </h1>

        {/* Content Container */}
        <div className="space-y-10 text-[#444] text-lg md:text-xl leading-relaxed">

          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p>
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name [BMSCCE] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Job Platform”).
          </p>

          <p>
            The Platform is owned by "Growsharp Technologies Pvt Ltd", a company incorporated under the Companies Act, 1956, with its registered office at [Outer Ring Rd, B Channasandra, Bennigana Halli, Bengaluru, Karnataka 560043] (hereinafter referred to as "Platform Owner," “we,” “us,” or “our”).
          </p>

          <p>
            Your use of the Platform, services, and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform, including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable for such transactions. By mere use of the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute your binding obligations with the Platform Owner.
          </p>
          <p>
            These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>
          <p>
            For the purpose of these Terms of Use, wherever the context so requires, "you", “your,” or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          <p className="font-bold text-lg md:text-3xl text-black">
            ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
          </p>
          {/* Sections */}
          <Section title="1. Accuracy of Information">
            To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
          </Section>

          <Section title="2. No Warranty">
            Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
          </Section>

          <Section title="3. At Your Own Risk">
            Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.

          </Section>

          <Section title="4. Intellectual Property">
            The contents of the Platform and the Services are proprietary to us and licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The content includes, but is not limited to, the design, layout, look, and graphics.
          </Section>

          <Section title="5. Unauthorized Use">
            You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
          </Section>

          <Section title="6. Service Charges">
            You agree to pay us the charges associated with availing the Services.

          </Section>

          <Section title="7. Lawful Use">
            You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or by Indian or local laws that might apply to you.

          </Section>

          <Section title="8. Third-Party Links">
            You acknowledge that the website and Services may contain links to third-party websites. Upon accessing these links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites. These links are provided for your convenience to provide further information.
          </Section>

          <Section title="9. Legally Binding Contract">
            You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
          </Section>

          <Section title="10. Indemnity">
            You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other Policies, or your violation of any law, rules, or regulations or the rights (including infringement of intellectual property rights) of a third party.          </Section>

          <Section title="11. Limitation of Liability">
            In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages, including without limitation, damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data, or loss of other economic interests, whether in contract, negligence, tort, or otherwise, arising from the use of or inability to use the Services. However, the Platform Owner's liability will not exceed the amount paid by you for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100), whichever is less.

          </Section>

          <Section title="12. Force Majeure">
            Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
          </Section>

          <Section title="13. Governing Law & Jurisdiction">
            These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in North 24 [Bengaluru, Karnataka]

          </Section>
          <Section title="14. Contact Information">
            All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.

          </Section>
          <p className="font-bold text-black pt-4">
            Please read these Terms carefully. If you do not agree, you must discontinue using our platform.
          </p>
          <p>
            For any concerns, please contact:
            <b> support@growsharptech.com</b>
          </p>

        </div>

      </div>
    </section>
  );
}

/* ------------------------- SECTION COMPONENT ------------------------- */

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-2">
      <h2 className="text-xl sm:text-2xl text-[#595959] font-semibold">{title}</h2>
      <p>{children}</p>
    </div>
  );
}
