export const PolicyCta = () => {
    return (
        <div className="max-w-6xl w-full mx-auto  flex flex-col md:flex-row items-center justify-center gap-4 py-10 px-2">
            <div className="border-2 border-[#011642] rounded-md py-10 px-4 space-y-4">
                <p className="text-3xl text-[#011642] font-bold">Terms and Conditions</p>
                <p>This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
            </div>
            <div className="border-2 border-[#011642]  rounded-md py-10 px-4 space-y-4">
                <p className="text-3xl text-[#011642]  font-bold">Privacy Policy</p>
                <p><b className="">Personal Information:</b> We collect personal details such as your name, email address, shipping address, phone number, and payment information when you make a purchase, create an account, or contact us.
                </p>
            </div>
        </div>
    )
}